[book]
authors = ["Willem Wyndham"]
language = "en"
multilingual = false
src = "src"
title = "RAEN Docs"

[output.html]
git-repository-url = "https://github.com/raendev/docs/tree/master"
edit-url-template  = "https://github.com/raendev/docs/tree/master/{path}"

[output.html.playground]
editable = true
line-numbers = true